### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by serhaterfidan** [threadsjs/threads.js#59]
TypeError: Cannot read properties of null (reading '0')
    at parseBloksResponse (/Users/serhaterfidan/Desktop/threadsapi/node_modules/@threadsjs/threads.js/src/util/Bloks.js:30:89)
    at Client.login (/Users/serhaterfidan/Desktop/threadsapi/node_modules/@threadsjs/threads.js/src/index.js:75:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/serhaterfidan/Desktop/threadsapi/server.js:17:5

**Comment by serhaterfidan** [comment]
version is 1.7.0

**Comment by AlexBSoft** [comment]
Same. Version 1.5.4

**Comment by mazenkourouche** [comment]
Same here v1.6.5

**Comment by elijah-wright** [comment]
password is probably wrong

**Comment by elijah-wright** [comment]
I'll look into it, give me a minute

**Comment by stevenlafl** [comment]
I just tested the most recent version and it worked for me.

**Comment by elijah-wright** [comment]
fixed in 1.7.1, thanks for pointing this out y'all
